name: Next.js Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21"

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Run Lint (check)
        run: npm run lint

      - name: Run Build
        run: npm run build
