name: Next.js Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.4.0

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
